### ISSUE TITLE
nuScenes training pipeline

### ISSUE THREAD

**Issue by faikit** [mit-han-lab/spvnas#98]
Thanks for sharing the code. Would you provide some training hyperparameters on the nuScenes dataset?

**Comment by zhijian-liu** [comment]
Sure. We use the following training hyperparameters on nuScenes:
```
optimizer:
  name: sgd
  lr: 2.4e-1
  weight_decay: 1.0e-4
  momentum: 0.9
  nesterov: true
```
